"""Add camera flags and face tables
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55e01ad1395f'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('access_control_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'access_control_enabled')
    # ### end Alembic commands ###
